baseURL = "https://vadlamaniuday.github.io/my-blog/"
languageCode = "en-us"
title = "Uday's Blog"
theme = "PaperMod"
enableRobotsTXT = true
googleAnalytics = "G-XXXXXXXXXX"

[params]
  description = "Thoughts on tech, data, and engineering"
  author = "Uday"

[taxonomies]
  tag = "tags"
  category = "categories"
